using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Database_Designer
{
    public static class RlsSqlGenerator
    {
        public sealed record Column(string Name, string PgType, bool IsPrimary);
        public sealed record Table(string Schema, string Name, IReadOnlyList<Column> Columns)
        {
            public string Qualified => string.IsNullOrEmpty(Schema) ? Name : $"{Schema}.{Name}";
            public string Sql => string.IsNullOrEmpty(Schema) ? Quote(Name) : $"{Quote(Schema)}.{Quote(Name)}";
        }

        public sealed record ResolvedPolicy(string Command, string Access, string OwnerColumn);

        private static readonly string[] OwnerCandidates =
        {
            "user_id", "owner_id", "created_by", "author_id", "seller_id", "account_id",
            "profile_id", "member_id", "sender_id", "buyer_id", "customer_id"
        };

        public static List<Table> FromProject(IEnumerable<global::DatabaseDesigner.SessionStorage.TableObject> tables) =>
            (tables ?? Enumerable.Empty<global::DatabaseDesigner.SessionStorage.TableObject>())
                .Select(t => new Table(
                    t.SchemaName,
                    t.TableName,
                    (t.Rows ?? new List<global::DatabaseDesigner.SessionStorage.RowCreation>())
                        .Select(r => new Column(r.Name ?? "", r.RowType?.ToString() ?? "", r.IsPrimary ?? false))
                        .ToList()))
                .ToList();

        public static ResolvedPolicy Resolve(RLSData.Policy policy, Table table)
        {
            var category = (policy.Category ?? "Base Server").Trim().ToLowerInvariant();
            var command = Normalize(policy.Command, RLSData.Commands) ?? category switch
            {
                "communication" => "SELECT",
                "profiles" => "ALL",
                "economy" => "ALL",
                _ => "SELECT"
            };
            var access = Normalize(policy.Access, RLSData.AccessRules) ?? category switch
            {
                "profiles" => "Public read, own writes",
                "economy" => "Own rows",
                "communication" => "Own rows",
                _ => "Everyone"
            };
            var owner = !string.IsNullOrWhiteSpace(policy.OwnerColumn) ? policy.OwnerColumn.Trim() : DetectOwnerColumn(table, category);
            return new ResolvedPolicy(command, access, owner);
        }

        public static string DetectOwnerColumn(Table table, string category = null)
        {
            if (table?.Columns == null) return null;
            var names = table.Columns.Select(c => c.Name).ToList();
            if (category == "communication")
            {
                var sender = names.FirstOrDefault(n => n.Equals("sender_id", StringComparison.OrdinalIgnoreCase));
                if (sender != null) return sender;
            }
            foreach (var cand in OwnerCandidates)
            {
                var hit = names.FirstOrDefault(n => n.Equals(cand, StringComparison.OrdinalIgnoreCase));
                if (hit != null) return hit;
            }
            var t = table.Name.ToLowerInvariant();
            if (t.Contains("user") || t.Contains("account") || t.Contains("profile"))
                return table.Columns.FirstOrDefault(c => c.IsPrimary)?.Name;
            return null;
        }

        public static string Generate(RLSData data, IReadOnlyList<Table> tables)
        {
            var sql = new StringBuilder();
            sql.AppendLine("-- ============================================================");
            sql.AppendLine("-- ROW LEVEL SECURITY (RLS)");
            sql.AppendLine("-- Auto-generated by Database Designer. Run after SQL.sql.");
            sql.AppendLine("--");
            sql.AppendLine("-- Per request, your API should (inside one connection/transaction):");
            sql.AppendLine("--   SELECT set_config('app.current_user_id', '<user id>', false);");
            sql.AppendLine("--   SELECT set_config('role', '<one of the roles below>', false);");
            sql.AppendLine("-- NodeWalker's \"DB: RLS Set User\" / \"DB: RLS Set Role\" blocks do exactly this.");
            sql.AppendLine("-- Superusers and roles with BYPASSRLS ignore every policy: connect");
            sql.AppendLine("-- your API with an ordinary login role that is a member of these roles.");
            sql.AppendLine("-- ============================================================");
            sql.AppendLine();

            var roles = (data?.Roles ?? new List<RLSData.PolicyRole>())
                .Where(r => r.Tables != null && r.Tables.Any(t => t.Policies?.Count > 0))
                .ToList();
            if (roles.Count == 0 || tables == null || tables.Count == 0)
            {
                sql.AppendLine("-- No RLS policies defined.");
                return sql.ToString();
            }

            var roleNames = roles.Select(r => RoleName(r.Name)).Distinct().ToList();
            AppendHelpers(sql, roleNames);

            sql.AppendLine("-- ------------------------------------------------------------");
            sql.AppendLine("-- Roles");
            sql.AppendLine("-- ------------------------------------------------------------");
            foreach (var role in roles)
            {
                var rn = RoleName(role.Name);
                if (!string.IsNullOrWhiteSpace(role.Description)) sql.AppendLine($"-- {rn}: {OneLine(role.Description)}");
                sql.AppendLine($"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{rn}') THEN CREATE ROLE {rn} NOLOGIN; END IF; END $$;");
            }
            sql.AppendLine();

            var baseRoles = roleNames.Where(r => r.Contains("standard") || r == "users" || r.EndsWith("_users") && !r.Contains("admin") && !r.Contains("moderator") && !r.Contains("bot")).ToList();
            var modRoles = roleNames.Where(r => r.Contains("moderator")).ToList();
            var adminRoles = roleNames.Where(r => r.Contains("admin")).ToList();
            var grants = new List<(string member, string of)>();
            foreach (var a in adminRoles) { grants.AddRange(baseRoles.Select(b => (a, b))); grants.AddRange(modRoles.Select(m => (a, m))); }
            foreach (var m in modRoles) grants.AddRange(baseRoles.Select(b => (m, b)));
            if (grants.Count > 0)
            {
                sql.AppendLine("-- Role hierarchy: admins inherit moderator + standard access, moderators inherit standard.");
                foreach (var (member, of) in grants.Distinct())
                    sql.AppendLine($"GRANT {of} TO {member};");
                sql.AppendLine();
            }

            var byTable = new Dictionary<Table, List<(RLSData.PolicyRole role, RLSData.TablePolicies tp)>>();
            foreach (var role in roles)
                foreach (var tp in role.Tables)
                {
                    if (tp.Policies == null || tp.Policies.Count == 0) continue;
                    var table = FindTable(tables, tp.TableName);
                    if (table == null)
                    {
                        sql.AppendLine($"-- SKIPPED: role {RoleName(role.Name)} has policies for '{tp.TableName}', which is not a table in this project.");
                        continue;
                    }
                    if (!byTable.TryGetValue(table, out var list)) byTable[table] = list = new();
                    list.Add((role, tp));
                }
            if (byTable.Count > 0 && sql[sql.Length - 1] != '\n') sql.AppendLine();

            foreach (var (table, entries) in byTable)
            {
                var q = table.Sql;
                sql.AppendLine("-- ============================================================");
                sql.AppendLine($"-- {q}");
                sql.AppendLine("-- ============================================================");
                sql.AppendLine($"ALTER TABLE {q} ENABLE ROW LEVEL SECURITY;");
                sql.AppendLine($"ALTER TABLE {q} FORCE ROW LEVEL SECURITY;");
                sql.AppendLine();

                var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                foreach (var (role, tp) in entries)
                {
                    var rn = RoleName(role.Name);
                    var privileges = new SortedSet<string>();
                    foreach (var policy in tp.Policies)
                    {
                        var r = Resolve(policy, table);
                        foreach (var p in PrivilegesFor(r)) privileges.Add(p);
                        AppendPolicy(sql, table, rn, policy, r, usedNames);
                    }

                    if (!string.IsNullOrEmpty(table.Schema))
                        sql.AppendLine($"GRANT USAGE ON SCHEMA {Quote(table.Schema)} TO {rn};");
                    sql.AppendLine($"GRANT {string.Join(", ", privileges)} ON {q} TO {rn};");
                    if (privileges.Contains("INSERT"))
                        sql.AppendLine($"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA {Quote(string.IsNullOrEmpty(table.Schema) ? "public" : table.Schema)} TO {rn};");
                    sql.AppendLine();
                }
            }

            return sql.ToString();
        }

        private static void AppendPolicy(StringBuilder sql, Table table, string role, RLSData.Policy policy, ResolvedPolicy r, HashSet<string> usedNames)
        {
            var baseName = Unique(usedNames, $"{role}_{PolicyName(policy.Name)}");
            sql.AppendLine($"-- Policy \"{policy.Name}\" ({policy.Category}): {r.Access}, {r.Command}" +
                           (string.IsNullOrWhiteSpace(policy.Tag) ? "" : $" [{policy.Tag}]"));
            if (!string.IsNullOrWhiteSpace(policy.Description) && !policy.Description.StartsWith("User Entered Description", StringComparison.Ordinal))
                sql.AppendLine($"-- {OneLine(policy.Description)}");

            string owner = OwnerExpr(table, r.OwnerColumn, out var ownerWarning);
            if (ownerWarning != null) sql.AppendLine($"-- WARNING: {ownerWarning}");

            switch (r.Access)
            {
                case "Public read, own writes":
                {
                    var readable = PublicReadExpr(table, owner);
                    Emit(sql, table, Unique(usedNames, baseName + "_read"), "SELECT", role, readable, null);
                    if (r.Command != "SELECT")
                    {
                        var writeCmd = r.Command == "ALL" ? "ALL" : r.Command;
                        Emit(sql, table, Unique(usedNames, baseName + "_write"), writeCmd, role, owner, owner);
                    }
                    break;
                }
                case "Custom SQL":
                {
                    var usingSql = string.IsNullOrWhiteSpace(policy.UsingSql) ? "false" : policy.UsingSql.Trim();
                    var checkSql = string.IsNullOrWhiteSpace(policy.CheckSql) ? usingSql : policy.CheckSql.Trim();
                    Emit(sql, table, baseName, r.Command, role, usingSql, checkSql);
                    break;
                }
                default:
                {
                    var rule = r.Access switch
                    {
                        "Everyone" => "true",
                        "Nobody" => "false",
                        _ => owner
                    };
                    Emit(sql, table, baseName, r.Command, role, rule, rule);
                    break;
                }
            }
            sql.AppendLine();
        }

        private static void Emit(StringBuilder sql, Table table, string name, string command, string role, string usingRule, string checkRule)
        {
            bool hasUsing = command is "ALL" or "SELECT" or "UPDATE" or "DELETE";
            bool hasCheck = command is "ALL" or "INSERT" or "UPDATE";
            var lines = new List<string>
            {
                $"CREATE POLICY \"{name}\" ON {table.Sql}",
                $"    AS PERMISSIVE FOR {command} TO {role}"
            };
            if (hasUsing) lines.Add($"    USING (is_admin() OR is_moderator() OR ({usingRule ?? "false"}))");
            if (hasCheck) lines.Add($"    WITH CHECK (is_admin() OR ({checkRule ?? usingRule ?? "false"}))");
            sql.AppendLine($"DROP POLICY IF EXISTS \"{name}\" ON {table.Sql};");
            sql.AppendLine(string.Join(Environment.NewLine, lines) + ";");
        }

        private static string OwnerExpr(Table table, string ownerColumn, out string warning)
        {
            warning = null;
            var col = table.Columns.FirstOrDefault(c => c.Name.Equals(ownerColumn ?? "", StringComparison.OrdinalIgnoreCase));
            if (col == null)
            {
                warning = string.IsNullOrWhiteSpace(ownerColumn)
                    ? $"{table.Qualified} has no owner column (e.g. user_id); rows are only visible to admins/moderators. Set Owner Column on the policy."
                    : $"owner column '{ownerColumn}' does not exist on {table.Qualified}; rows are only visible to admins/moderators.";
                return "false";
            }
            var t = (col.PgType ?? "").ToLowerInvariant();
            if (t.Contains("uuid")) return $"{col.Name} = current_user_uuid()";
            if (t.Contains("char") || t.Contains("text")) return $"{col.Name} = current_setting('app.current_user_id', true)";
            return $"{col.Name} = current_user_id()";
        }

        private static string PublicReadExpr(Table table, string owner)
        {
            var parts = new List<string>();
            if (Has(table, "is_public")) parts.Add("is_public = true");
            if (Has(table, "visibility")) parts.Add("visibility = 'public'");
            if (parts.Count == 0) return "true";
            if (owner != "false") parts.Add(owner);
            return string.Join(" OR ", parts);
        }

        private static IEnumerable<string> PrivilegesFor(ResolvedPolicy r)
        {
            if (r.Access == "Public read, own writes")
                return r.Command == "SELECT" ? new[] { "SELECT" } : r.Command == "ALL" ? new[] { "SELECT", "INSERT", "UPDATE", "DELETE" } : new[] { "SELECT", r.Command };
            return r.Command == "ALL" ? new[] { "SELECT", "INSERT", "UPDATE", "DELETE" } : new[] { r.Command };
        }

        private static void AppendHelpers(StringBuilder sql, List<string> roleNames)
        {
            var admins = roleNames.Where(r => r.Contains("admin")).ToList();
            var mods = roleNames.Where(r => r.Contains("moderator")).ToList();
            string InList(IEnumerable<string> names) =>
                string.Join(", ", names.Concat(new[] { "admin" }).Distinct().Select(n => $"'{n}'"));

            sql.AppendLine("-- ------------------------------------------------------------");
            sql.AppendLine("-- Helper functions (policies below depend on these)");
            sql.AppendLine("-- ------------------------------------------------------------");
            sql.AppendLine(@"CREATE OR REPLACE FUNCTION current_user_id() RETURNS BIGINT
LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_user_id', true), '')::BIGINT;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION current_user_uuid() RETURNS UUID
LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_user_id', true), '')::UUID;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION current_app_role() RETURNS TEXT
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(NULLIF(current_setting('app.current_user_role', true), ''), current_user::text);
$$;
");
            sql.AppendLine($@"CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN
LANGUAGE sql STABLE AS $$
    SELECT current_app_role() IN ({InList(admins)});
$$;

CREATE OR REPLACE FUNCTION is_moderator() RETURNS BOOLEAN
LANGUAGE sql STABLE AS $$
    SELECT is_admin() OR current_app_role() IN ({InList(mods.Any() ? mods : new List<string> { "moderator" })});
$$;
");
        }


        private static Table FindTable(IReadOnlyList<Table> tables, string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return null;
            var n = name.Trim();
            return tables.FirstOrDefault(t => t.Qualified.Equals(n, StringComparison.OrdinalIgnoreCase))
                ?? tables.FirstOrDefault(t => t.Name.Equals(n, StringComparison.OrdinalIgnoreCase))
                ?? tables.FirstOrDefault(t => n.Contains('.') && t.Name.Equals(n.Split('.').Last(), StringComparison.OrdinalIgnoreCase));
        }

        private static bool Has(Table t, string col) =>
            t.Columns.Any(c => c.Name.Equals(col, StringComparison.OrdinalIgnoreCase));

        private static string Normalize(string value, string[] allowed) =>
            string.IsNullOrWhiteSpace(value) ? null
            : allowed.FirstOrDefault(a => a.Equals(value.Trim(), StringComparison.OrdinalIgnoreCase));

        public static string RoleName(string name)
        {
            var sb = new StringBuilder();
            foreach (var c in (name ?? "").Trim().ToLowerInvariant())
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            var s = System.Text.RegularExpressions.Regex.Replace(sb.ToString(), "_+", "_").Trim('_');
            if (s.Length == 0) return "standard_users";
            return char.IsDigit(s[0]) ? "r_" + s : s;
        }

        private static string PolicyName(string name)
        {
            var sb = new StringBuilder();
            foreach (var c in (name ?? "").Trim().ToLowerInvariant())
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            var s = System.Text.RegularExpressions.Regex.Replace(sb.ToString(), "_+", "_").Trim('_');
            return s.Length == 0 ? "policy" : s;
        }

        private static string Unique(HashSet<string> used, string name)
        {
            if (name.Length > 60) name = name.Substring(0, 60);
            var candidate = name;
            for (int i = 2; !used.Add(candidate); i++) candidate = $"{name}_{i}";
            return candidate;
        }

        private static string Quote(string ident) => "\"" + (ident ?? "").Replace("\"", "\"\"") + "\"";

        private static string OneLine(string s) => (s ?? "").Replace("\r", " ").Replace("\n", " ").Trim();
    }
}
