using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using DatabaseDesigner;
using static DatabaseDesigner.SessionStorage;
using PT = DatabaseDesigner.DBDesigner.PostgresType;

namespace Database_Designer
{
    // Makes believable test rows for every table. Parents are filled before
    // the tables that reference them, and a foreign key picks an existing
    // parent row, so the INSERTs succeed on a database built from SQL.sql.
    public static class SampleDataGenerator
    {
        public sealed class Result
        {
            public string Sql { get; set; }
            public List<(string Table, string Statement)> Statements { get; } = new();
            public List<string> Warnings { get; } = new();
        }

        private static readonly string[] First = { "Ava", "Liam", "Mia", "Noah", "Zoe", "Ethan", "Ivy", "Lucas", "Nora", "Omar", "Priya", "Kenji", "Sofia", "Mateo", "Amara", "Jonas" };
        private static readonly string[] Last = { "Walker", "Chen", "Garcia", "Okafor", "Novak", "Silva", "Kim", "Patel", "Rossi", "Haddad", "Larsen", "Ito", "Moreau", "Diaz", "Nguyen", "Brooks" };
        private static readonly string[] Products = { "Desk Lamp", "Canvas Tote", "Ceramic Mug", "Wool Scarf", "Notebook", "Water Bottle", "Headphones", "Plant Pot", "Phone Stand", "Backpack", "Candle", "Throw Blanket", "Keyboard", "Sunglasses", "Tea Sampler", "Board Game" };
        private static readonly string[] Words = { "quick", "simple", "bright", "quiet", "handmade", "classic", "fresh", "compact", "sturdy", "soft", "modern", "vintage" };
        private static readonly string[] Cities = { "Lisbon", "Osaka", "Toronto", "Nairobi", "Austin", "Berlin", "Melbourne", "Bogotá" };
        private static readonly string[] Countries = { "PT", "JP", "CA", "KE", "US", "DE", "AU", "CO" };
        private static readonly string[] Colors = { "red", "blue", "green", "black", "white", "yellow" };

        public static Result Generate(IEnumerable<TableObject> tablesIn, int rowsPerTable = 10)
        {
            var result = new Result();
            rowsPerTable = Math.Max(1, Math.Min(1000, rowsPerTable));
            var tables = (tablesIn ?? Enumerable.Empty<TableObject>())
                .Where(t => !string.IsNullOrEmpty(t.TableName) && (t.Rows?.Count ?? 0) > 0).ToList();
            var byName = tables.GroupBy(Q, StringComparer.OrdinalIgnoreCase).ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

            var ordered = Order(tables, byName, result.Warnings);
            var filled = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var sb = new StringBuilder();
            sb.AppendLine("-- Sample data generated by Database Designer.");
            sb.AppendLine("-- Safe to run more than once: rows that clash with existing unique values are skipped.");
            sb.AppendLine();

            int tableIndex = 0;
            foreach (var t in ordered)
            {
                var rnd = new Random(1234 + tableIndex++);
                var refs = (t.References ?? new()).Where(r => r.ForeignKey != null)
                    .GroupBy(r => r.ForeignKey, StringComparer.OrdinalIgnoreCase).ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

                var columns = new List<RowCreation>();
                foreach (var c in t.Rows)
                {
                    if (string.IsNullOrWhiteSpace(c.Name)) continue;
                    if (c.RowType is PT.Serial or PT.BigSerial or PT.SmallSerial) continue;
                    // Function defaults (now(), gen_random_uuid()) are left to
                    // the database; constant defaults get varied sample values.
                    bool functionDefault = !string.IsNullOrWhiteSpace(c.DefaultValue) &&
                        (c.DefaultIsPostgresFunction == true || c.DefaultValue.Contains('('));
                    if (functionDefault && !refs.ContainsKey(c.Name)) continue;
                    columns.Add(c);
                }
                if (columns.Count == 0)
                {
                    sb.AppendLine($"-- {Q(t)}: every column has a default; inserting default rows.");
                    var stmt = string.Join("\n", Enumerable.Range(0, rowsPerTable).Select(_ => $"INSERT INTO {Table(t)} DEFAULT VALUES;"));
                    sb.AppendLine(stmt).AppendLine();
                    result.Statements.Add((Q(t), stmt));
                    filled.Add(Q(t));
                    continue;
                }

                var rows = new List<string>();
                bool skipTable = false;
                for (int i = 0; i < rowsPerTable && !skipTable; i++)
                {
                    var values = new List<string>();
                    foreach (var c in columns)
                    {
                        if (refs.TryGetValue(c.Name, out var rf))
                        {
                            values.Add(ForeignValue(t, c, rf, i, rowsPerTable, byName, filled, result.Warnings, ref skipTable));
                            continue;
                        }
                        var v = Value(t, c, i, rnd, out var warn);
                        if (warn != null && i == 0) result.Warnings.Add($"{Q(t)}.{c.Name}: {warn}");
                        values.Add(v);
                    }
                    rows.Add("    (" + string.Join(", ", values) + ")");
                }
                if (skipTable) continue;

                var insert = $"INSERT INTO {Table(t)} ({string.Join(", ", columns.Select(c => Col(c.Name)))}) VALUES\n" +
                             string.Join(",\n", rows) + "\nON CONFLICT DO NOTHING;";
                sb.AppendLine($"-- {Q(t)}");
                sb.AppendLine(insert).AppendLine();
                result.Statements.Add((Q(t), insert));
                filled.Add(Q(t));
            }

            result.Sql = sb.ToString();
            return result;
        }

        public static string Q(TableObject t) => string.IsNullOrEmpty(t.SchemaName) ? t.TableName : $"{t.SchemaName}.{t.TableName}";

        private static string Table(TableObject t) =>
            string.IsNullOrEmpty(t.SchemaName) ? $"\"{t.TableName}\"" : $"\"{t.SchemaName}\".\"{t.TableName}\"";

        // Columns are written unquoted in SQL.sql, so Postgres folds them to
        // lower case; refer to them the same way.
        private static string Col(string name) =>
            Regex.IsMatch(name, @"^[A-Za-z_][A-Za-z0-9_]*$") ? name : "\"" + name.Replace("\"", "\"\"") + "\"";

        private static List<TableObject> Order(List<TableObject> tables, Dictionary<string, TableObject> byName, List<string> warnings)
        {
            var result = new List<TableObject>();
            var state = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            void Visit(TableObject t)
            {
                var k = Q(t);
                if (state.TryGetValue(k, out var s))
                {
                    if (s == 1) warnings.Add($"{k} is part of a reference loop; some of its foreign keys may be left empty.");
                    return;
                }
                state[k] = 1;
                foreach (var r in t.References ?? new())
                    if (r.RefTable != null && byName.TryGetValue(r.RefTable, out var parent) && !string.Equals(Q(parent), k, StringComparison.OrdinalIgnoreCase))
                        Visit(parent);
                state[k] = 2;
                result.Add(t);
            }
            foreach (var t in tables.OrderBy(Q, StringComparer.OrdinalIgnoreCase)) Visit(t);
            return result;
        }

        private static string ForeignValue(TableObject t, RowCreation c, ReferenceOptions rf, int i, int n,
            Dictionary<string, TableObject> byName, HashSet<string> filled, List<string> warnings, ref bool skipTable)
        {
            bool required = c.IsNotNull == true || c.IsPrimary == true;
            if (rf.RefTable == null || !byName.TryGetValue(rf.RefTable, out var parent))
            {
                if (i == 0) warnings.Add($"{Q(t)}.{c.Name}: references {rf.RefTable}, which isn't in the project.");
                if (required) { skipTable = true; if (i == 0) warnings.Add($"{Q(t)} skipped."); }
                return "NULL";
            }
            bool self = string.Equals(Q(parent), Q(t), StringComparison.OrdinalIgnoreCase);
            if (self || !filled.Contains(Q(parent)))
            {
                if (required)
                {
                    skipTable = true;
                    if (i == 0) warnings.Add($"{Q(t)} skipped: {c.Name} must point at a row in {Q(parent)}, which has no sample rows{(self ? " yet (it points at its own table)" : "")}.");
                }
                return "NULL";
            }
            var key = Col(rf.RefTableKey ?? "id");
            // Spread rows across the parents in order; with as many children as
            // parents this also keeps a unique (1:1) foreign key unique.
            return $"(SELECT {key} FROM {Table(parent)} ORDER BY {key} OFFSET {i % n} LIMIT 1)";
        }

        private static string Value(TableObject t, RowCreation c, int i, Random rnd, out string warning)
        {
            warning = null;
            var name = (c.Name ?? "").ToLowerInvariant();
            var table = (t.TableName ?? "").ToLowerInvariant();
            bool unique = c.IsUnique == true || c.IsPrimary == true;
            if (c.IsArray == true) return "'{}'";

            var options = CheckOptions(c.Check);
            if (options.Count > 0) return Lit(options[i % options.Count]);

            switch (c.RowType ?? (c.Media == true ? PT.SecureMedia : PT.Text))
            {
                case PT.SmallInt: return Int(name, i, rnd, unique, 30000).ToString(CultureInfo.InvariantCulture);
                case PT.Integer: return Int(name, i, rnd, unique, int.MaxValue).ToString(CultureInfo.InvariantCulture);
                case PT.BigInt: return Int(name, i, rnd, unique, int.MaxValue).ToString(CultureInfo.InvariantCulture);
                case PT.Real:
                case PT.DoublePrecision:
                case PT.Numeric:
                case PT.Money:
                    return Dec(name, i, rnd, c.Limit);
                case PT.Boolean: return i % 3 == 2 ? "false" : "true";
                case PT.Uuid: return "gen_random_uuid()";
                case PT.Date: return $"(current_date - {i * 3})";
                case PT.Time: return Lit($"{9 + i % 9:00}:{(i * 7) % 60:00}");
                case PT.TimeTz: return Lit($"{9 + i % 9:00}:{(i * 7) % 60:00}+00");
                case PT.Timestamp: return $"(now()::timestamp - interval '{i * 26} hours')";
                case PT.TimestampTz: return $"(now() - interval '{i * 26} hours')";
                case PT.Interval: return Lit($"{1 + i % 12} hours");
                case PT.Json:
                case PT.Jsonb: return Lit($"{{\"sample\": {i + 1}}}");
                case PT.Inet: return Lit($"192.168.{i / 250}.{i % 250 + 1}");
                case PT.Cidr: return Lit($"10.{i / 250}.{i % 250}.0/24");
                case PT.MacAddr: return Lit($"08:00:2b:01:{i / 256:x2}:{i % 256:x2}");
                case PT.Bytea: return "decode('00', 'hex')";
                case PT.Xml: return Lit($"<sample id=\"{i + 1}\"/>");
                case PT.TsVector: return $"to_tsvector('simple', {Lit(Pick(Words, i) + " " + Pick(Products, i))})";
                case PT.TsQuery: return $"to_tsquery('simple', {Lit(Pick(Words, i))})";
                case PT.Point: return $"point({i}, {i * 2})";
                case PT.Int4RangeBase:
                case PT.Int8RangeBase: return Lit($"[{i},{i + 10})");
                case PT.NumRangeBase: return Lit($"[{i}.5,{i + 10}.5)");
                case PT.DateRangeBase: return $"daterange(current_date - {i + 7}, current_date - {i})";
                case PT.TsRangeBase: return $"tsrange(now()::timestamp - interval '{i + 7} days', now()::timestamp - interval '{i} days')";
                case PT.TstzRangeBase: return $"tstzrange(now() - interval '{i + 7} days', now() - interval '{i} days')";
                case PT.CustomComposite:
                case PT.CustomEnum:
                case PT.CustomDomain:
                case PT.SecureMedia:
                    warning = "custom/media type, left empty";
                    return "NULL";
                default:
                    return Lit(Fit(Text(name, table, i, rnd, unique), c, i, unique));
            }
        }

        private static long Int(string name, int i, Random rnd, bool unique, long max)
        {
            if (unique || name == "id" || name.EndsWith("_id")) return i + 1;
            long v = name switch
            {
                _ when Has(name, "qty", "quantity", "stock", "count", "inventory") => rnd.Next(1, 50),
                _ when Has(name, "age") => rnd.Next(18, 80),
                _ when Has(name, "rating", "score", "stars") => rnd.Next(1, 6),
                _ when Has(name, "year") => rnd.Next(2000, 2026),
                _ when Has(name, "price", "amount", "total", "cost", "cents") => rnd.Next(100, 50000),
                _ when Has(name, "order", "position", "rank", "sort") => i + 1,
                _ => rnd.Next(1, 1000)
            };
            return Math.Min(v, max);
        }

        private static string Dec(string name, int i, Random rnd, int? limit)
        {
            double v = Has(name, "price", "amount", "total", "cost", "balance", "fee")
                ? Math.Round(rnd.NextDouble() * 200 + 2, 2)
                : Has(name, "rating", "score") ? Math.Round(rnd.NextDouble() * 4 + 1, 1)
                : Has(name, "lat") ? Math.Round(rnd.NextDouble() * 120 - 60, 5)
                : Has(name, "lng", "lon") ? Math.Round(rnd.NextDouble() * 300 - 150, 5)
                : Math.Round(rnd.NextDouble() * 100, 2);
            if (limit is > 0 && Row.LimitEncoder.TryDecodeTuple(limit.Value, out var p, out var s))
            {
                double max = Math.Pow(10, p - s) - Math.Pow(10, -s);
                v = Math.Round(Math.Min(Math.Abs(v), max), s);
            }
            return v.ToString("0.#####", CultureInfo.InvariantCulture);
        }

        private static string Text(string name, string table, int i, Random rnd, bool unique)
        {
            string first = Pick(First, i), last = Pick(Last, i * 7 + 3);
            string v =
                Has(name, "email") ? $"{first.ToLowerInvariant()}.{last.ToLowerInvariant()}{i + 1}@example.com" :
                Has(name, "username", "user_name", "login", "handle", "nickname") ? $"{first.ToLowerInvariant()}{i + 1}" :
                Has(name, "first_name", "firstname", "given") ? first :
                Has(name, "last_name", "lastname", "surname", "family") ? last :
                Has(name, "password", "hash", "secret") ? $"not-a-real-hash-{i + 1}" :
                Has(name, "url", "website", "link", "image", "avatar", "photo") ? $"https://example.com/{table}/{i + 1}" :
                Has(name, "phone", "mobile") ? $"+1-555-01{i % 100:00}" :
                Has(name, "sku", "code", "slug") ? $"{table.ToUpperInvariant().Substring(0, Math.Min(3, table.Length))}-{i + 1:0000}" :
                Has(name, "city") ? Pick(Cities, i) :
                Has(name, "country") ? Pick(Countries, i) :
                Has(name, "address", "street") ? $"{10 + i * 7} Main Street" :
                Has(name, "zip", "postal") ? $"{10000 + i * 137}" :
                Has(name, "currency") ? "usd" :
                Has(name, "color", "colour") ? Pick(Colors, i) :
                Has(name, "status", "state") ? Pick(new[] { "active", "pending", "done" }, i) :
                Has(name, "token", "ref", "key", "external") ? $"{name}_{rnd.Next(0x100000, 0xFFFFFF):x6}{i:x2}" :
                Has(name, "description", "bio", "about", "notes", "note", "comment", "body", "content", "message", "summary") ?
                    $"A {Pick(Words, i)} {Pick(Words, i + 5)} sample for testing (row {i + 1})." :
                Has(name, "title", "subject", "headline") ? $"{Cap(Pick(Words, i))} {Pick(Products, i)}" :
                Has(name, "name") && (Has(table, "product", "item", "listing", "good", "inventory")) ? Pick(Products, i) :
                Has(name, "name") && Has(table, "user", "customer", "member", "person", "people", "author", "employee", "account", "profile") ? $"{first} {last}" :
                Has(name, "name") ? $"{Cap(table.TrimEnd('s'))} {i + 1}" :
                $"{name} {i + 1}";
            if (unique && !v.Contains((i + 1).ToString(CultureInfo.InvariantCulture))) v += $" {i + 1}";
            return v;
        }

        private static string Fit(string v, RowCreation c, int i, bool unique)
        {
            if (c.Limit is > 0 && c.RowType is PT.VarChar or PT.Char && v.Length > c.Limit.Value)
            {
                int keep = c.Limit.Value;
                // A unique column must stay unique after cutting, so end with the row number.
                var suffix = unique ? (i + 1).ToString(CultureInfo.InvariantCulture) : "";
                v = suffix.Length > 0 && suffix.Length < keep
                    ? v.Substring(0, keep - suffix.Length) + suffix
                    : v.Substring(0, keep);
            }
            return v;
        }

        // CHECK (status IN ('a', 'b')) -> ["a", "b"]
        private static List<string> CheckOptions(string check)
        {
            var list = new List<string>();
            if (string.IsNullOrWhiteSpace(check)) return list;
            var m = Regex.Match(check, @"\bIN\s*\(([^)]*)\)", RegexOptions.IgnoreCase);
            if (!m.Success) return list;
            foreach (Match lit in Regex.Matches(m.Groups[1].Value, @"'((?:[^']|'')*)'"))
                list.Add(lit.Groups[1].Value.Replace("''", "'"));
            return list;
        }

        private static bool Has(string s, params string[] parts) => parts.Any(p => s.Contains(p));
        private static string Pick(string[] list, int i) => list[((i % list.Length) + list.Length) % list.Length];
        private static string Cap(string s) => string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s.Substring(1);
        private static string Lit(string s) => "'" + (s ?? "").Replace("'", "''") + "'";
    }
}
